### ISSUE TITLE
Missing Build Assets

### ISSUE THREAD

**Issue by bharu31** [humanmade/ai-plugin#3]
I tried installing in multiple instance of WP and it seems the Build folder is missing. 

The main readme in this repo also seems to be incomplete. There is only a header named usage and no instructions. 

Please have a look. 

[28-Feb-2024 01:17:35 UTC] PHP Fatal error:  Uncaught Error: Failed opening required 'D:\test\wp-content\plugins\ai-plugin-main\inc\dashboard-assistant\admin/build/index.tsx.asset.php' (include_path='.;D:/laragon/etc/php/pear') in D:\test\wp-content\plugins\ai-plugin-main\inc\dashboard-assistant\admin\namespace.php:11
Stack trace:
#0 D:\test\wp-includes\class-wp-hook.php(307): AI\Dashboard_Assistant\Admin\enqueue_admin_script('')
#1 D:\test\manufacts\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 D:\test\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
#3 D:\test\wp-admin\admin-header.php(139): do_action('admin_print_scr...')
#4 D:\test\wp-admin\admin.php(239): require_once('D:\\laragon\\www\\...')
#5 D:\test\wp-admin\index.php(10): require_once('D:\\laragon\\www\\...')

**Comment by tomjn** [comment]
The plugin repo doesn't include built assets, you need to build them yourself. If we did provide prebuilt packages it'd be on .org or they'd be available at https://github.com/humanmade/ai-plugin/releases which is currently empty.

I'm not familiar with the plugins specifics but there's a `composer.json` in the root and a `package.json` here https://github.com/humanmade/ai-plugin/blob/main/inc/gutenberg-assistant/admin/package.json and here: https://github.com/humanmade/ai-plugin/blob/main/inc/dashboard-assistant/admin/package.json as well as a few other places. All of those use WP Scripts to power the build process.

**Comment by tomjn** [comment]
I'm going to close this out as there aren't any plans to add pre-built assets into the repo

**Comment by bharu31** [comment]
Thanks Tom! Are there any instructions on how to build the assets. or would it be possible to request that pre-build assets be loaded to the repo. 
Also, the readme of the repo seems be incomplete with the usage and features heading added, but without any instructions. please have a look.
